spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/derbycounty
    username: postgres
    password: Hhaarryy10
    driverClassName: org.postgresql.Driver

  # Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  error:
    include-message: always
