spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/derbycounty
    username: postgres
    password: ${DB_password}
    driverClassName: org.postgresql.Driver

  # Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format_sql: true

server:
  error:
    include-message: always

logging:
  level:
    org:
      springframework:
        security: DEBUG